### ISSUE TITLE
Bedre feedback hvis et hold ikke er gyldigt. 

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#11]
Jeg får ikke en fejl selvom jeg forsøger at lave fejl på opstilling mellem holdene.

Der er fejl når opstillingen ikke passer internt på holdet.

![billede](https://user-images.githubusercontent.com/90771586/133446241-21f06cb7-9d98-466d-bda4-a1056e79cd52.png)

**Comment by sazo** [comment]
![image](https://user-images.githubusercontent.com/1503054/133461364-408a2d45-2214-48e5-8681-877abb3d5ce0.png)

@J-Kamp Grunden til at den ikke mærkere skyldes hold 2 og hold 3 ikke er valide hold. Når jeg bytter Frida og Astrid rundt i DD også, vises der fejl.

Så vil mene at der skal laves noget feedback om hold er valide.

**Comment by J-Kamp** [comment]
Arghh..

Ja, så er er der en ting, der kan tilføjes - den tænkte jeg ikke lige over også at bytte.. :-)
