### ISSUE TITLE
Fejl ved import - Tjek holdkamps runde

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#15]
Manglende spiller for modstander gør, at holdet ikke kan loades (og tjekkes).

![billede](https://user-images.githubusercontent.com/90771586/134633309-f03fdb74-e9c1-401b-bac7-f5b45a193320.png)

abc Aalborgs hold burde stadig kunne tjekkes når de har stillet op til kampen?

![billede](https://user-images.githubusercontent.com/90771586/134633363-7002369d-b3ab-4c98-842b-838d3baee250.png)

**Comment by sazo** [comment]
Det her issue er en dublet af https://github.com/flycompanytech/holdkamp-project/issues/5. Lukker denne.
