### ISSUE TITLE
U17/U19 spiller giver fejl i opstilling ved tjek

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#30]
Se 6. runde for Højbjerg - der bruges forskellige ranglister for 2. og 5. holdet.
Signe står til at være ulovlig på Højbjerg 2, men det er i forhold til Clara Løber (U17/U19).

![billede](https://user-images.githubusercontent.com/90771586/146161301-c2d461b4-24b8-461a-99a6-186a9236b61c.png)

**Comment by J-Kamp** [comment]
Samme problem, hvis Solrød 2 og 3 tjekkes for runde 6.
(Anna Bygum - Maria Højlund Tommerup)

![billede](https://user-images.githubusercontent.com/90771586/146161854-69bfdd57-ea82-4b18-a271-da2fe87cd84c.png)

**Comment by sazo** [comment]
Modtaget. :) Kigger jeg lige ind i. Noget jeg må misse.

**Comment by sazo** [comment]
![image](https://user-images.githubusercontent.com/1503054/146248939-6269e1af-3c07-4cfe-9362-5b4c0de28fd5.png)
![image](https://user-images.githubusercontent.com/1503054/146249121-1c662091-6b2a-4353-9a84-40dbe6a4b9e4.png)
Skulle gerne være fixed nu. Alle U17/U19 er nu "frie"
