### ISSUE TITLE
U17/U19 spillere

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#6]
U17 og U19 spillere skal ikke opstilles efter ranglisten...

De MÅ opstilles efter niveau, hvis ranglisten ikke er retvisende..

Forslag: Forsat markering af fejl i opstilling, men hvis der er tale om U17/U19 spiller farves de i en anden farve.

**Comment by sazo** [comment]
NTS: Glæder kun for DH turneringen. Kredsene har deres egne regler

**Comment by sazo** [comment]
![Screenshot from 2021-09-22 21-34-25](https://user-images.githubusercontent.com/1503054/134411061-f2e67fa9-67a6-4b78-82e9-070e82ef57f5.png)

Spiller som spiller for højt OG er U17 og U19 spiller er nu mærkeret med grøn .
