### ISSUE TITLE
Spiller-id på spillerne

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#8]
Tilføj spiller-id på hver enkelt spiller når man tjekker holdkampen.

**Comment by sazo** [comment]
@J-Kamp Hvad er det du ønsker at opnå? Ønsker du muligheden for at kopier det eller hvad tænkte du på da du oprettede issuet? :)

**Comment by J-Kamp** [comment]
Det var egentligt mest fordi jeg ville ind og tjekke en spille, så det er lidt overflødigt nu der er link til BP på siden.. :-)

Lad os sige, at den ikke er nødvendig længere! :-)
