### ISSUE TITLE
Gyldighed af reglerne

### ISSUE THREAD

**Issue by J-Kamp** [flycompanytech/holdkamp-project#9]
De anvendte kriterier gælder overordnet set kun i DH turneringen (2. div - Danmarksserien).

Kredsserie og serie 1 administreres af de enkelte kredse, som (måske) har andre regler for holdsætning, så det er farligt at sige, at det er gyldigt helt ned i serierne...

Det er noget bøvl at tjekke igennem!

**Comment by sazo** [comment]
@J-Kamp Tænker du det er ok at skrive "De anvendte kriterier gælder overordnet set i DH turneringen (2. div - Danmarksserien).".

**Comment by J-Kamp** [comment]
De anvendte kriterier er opsat jf. Holdturneringsreglementet i DH turneringen fra 2. division til Danmarksserien. 
De enkelte kredse har deres egne regler i forhold til anvendelse af rangliste og derfor kan værktøjet kun bruges vejledende under Danmarksserien.

https://badminton.dk/om-badminton-danmark/love-regler/reglementer/holdturneringer/
Tjek også de to vejledninger til holdsætning, der er på siden. Det kan måske bruges til at få implementeret liga og 1. div? :-)
